publijob/urls.py
from django.conf import settings
from django.contrib import admin

from django.urls import include, path
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("vacancies.urls")),
    path("", include("user.urls")),
    path("summernote/", include("django_summernote.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views


app_name = "user"

urlpatterns = [
    path("user/register/", views.UserRegister.as_view(), name="user_register"),
    path("user/login/", views.UserLogin.as_view(), name="user_login"),
    path("user/logout/", views.UserLogout.as_view(), name="user_logout"),
    path("user/view_profile/", views.UserProfile.as_view(), name="user_profile"),
    path("user/edit_user/", views.EditUserInformation.as_view(), name="edit_user"),
    path(
        "profile/<int:id>/update/",
        views.edit_profile_information,
        name="update_profile",
    ),
    path(
        "user/change_password/", views.ChangePassword.as_view(), name="change_password"
    ),
]

vacancies/urls.py
from django.urls import path
from . import views


app_name = "vacancies"

urlpatterns = [
    path("", views.VacancyHome.as_view(), name="home"),
    path("vacancy/<int:pk>", views.vacancy_detail_view, name="vacancy_detail"),
    path("search/", views.VacancySearch.as_view(), name="vacancy_search"),
    path("my_vacancies/", views.MyVacancies.as_view(), name="my_vacancies"),
    path("my_vacancies/delete/<int:pk>", views.delete_vacancy, name="delete_vacancy"),
    path(
        "vacancy_category/<str:category>",
        views.VacancyCategory.as_view(),
        name="vacancy_category",
    ),
    path(
        "filter/by-state/<str:state>",
        views.VacancyStateFilter.as_view(),
        name="state_filter",
    ),
    path("send_vacancy/", views.send_vacancy, name="send_vacancy"),
]

vacancies/models.py
from django.db import models
from categories.models import Category
from occupation.models import Occupation
from state.models import State
from django.contrib.auth.models import User


class Vacancy(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField("Name", max_length=255)
    visibility = models.BooleanField("Visible", default=False)
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    contact_number = models.PositiveBigIntegerField("Phone number")
    contact_whatsapp = models.PositiveBigIntegerField("WhatsApp")
    contact_email = models.EmailField("E-mail")
    occupation_area = models.ForeignKey(Occupation, on_delete=models.CASCADE)
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    city = models.CharField("City", max_length=255)
    number = models.IntegerField("Vacancies number", default=0)
    date_posted = models.DateTimeField(auto_now=True)
    img = models.ImageField(
        "Image", upload_to="vacancies_img/%Y/%m/%d", blank=True, null=True
    )
    salary = models.CharField("Salary", max_length=255)
    about_company = models.TextField("About the company")
    requirements = models.TextField("Requirements")
    activities = models.TextField("Activities")
    benefits = models.TextField("Benefits", blank=True, null=True)
    schedule = models.TextField("Schedule")

    def __str__(self) -> str:
        return self.name

vacancies/forms.py
from django import forms
from .models import Vacancy


class VacancyForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        if user:
            self.user = user

    class Meta:
        model = Vacancy
        exclude = ["visibility", "owner"]

vacancies/views.py
from vacancies.models import Vacancy
from .forms import VacancyForm
from django.views.generic.list import ListView
from django.shortcuts import render, redirect
from django.db.models import Q
from django.contrib import messages


class VacancyHome(ListView):
    model = Vacancy
    template_name = "vacancies/index.html"
    context_object_name = "vacancies"

    def get_queryset(self):
        return Vacancy.objects.filter(visibility=True)


def vacancy_detail_view(request, pk):
    context = {}
    context["vacancy"] = Vacancy.objects.get(id=pk)
    return render(request, "vacancies/detail.html", context)


class MyVacancies(ListView):
    model = Vacancy
    context_object_name = "vacancies"
    template_name = "vacancies/my_vacancies.html"

    def get_queryset(self):
        qs = Vacancy.objects.filter(owner=self.request.user)
        return qs

    def vacancies_exisist(self, *args, **kwargs):
        queryset = self.get_queryset()
        if not queryset.exists():
            messages.info(self.request, "you have no vacancies")

            return redirect("vacancies:send_vacancy")
        return super().get(self.request, *args, **kwargs)


class VacancySearch(VacancyHome):
    template_name = "vacancies/search.html"

    def get_queryset(self):
        qs = Vacancy.objects.filter(visibility=True)

        search = self.request.GET.get("search")
        occupation = self.request.GET.get("occupation")
        state = self.request.GET.get("state")

        if occupation and search and state:
            qs = qs.filter(
                Q(occupation_area__name=occupation)
                & Q(search__icontains=search)
                & Q(state__name=state)
            )
            return qs

        if occupation and search:
            qs = qs.filter(
                Q(occupation_area__name=occupation) & Q(name__icontains=search)
            )
            return qs

        if state and search:
            qs = qs.filter(Q(state__name=state) & Q(name__icontains=search))
            return qs

        if occupation and state:
            qs = qs.filter(Q(occupation_area__name=occupation) & Q(state__name=state))
            return qs

        if occupation:
            qs = qs.filter(Q(occupation_area__name=occupation))
            return qs

        if state:
            qs = qs.filter(Q(state__name=state))
            return qs

        if search:
            qs = qs.filter(Q(name__icontains=search))
            return qs
        return qs


class VacancyCategory(VacancyHome):
    template_name = "vacancies/vacancy_category.html"

    def get_queryset(self):
        category = self.kwargs.get("category", None)

        qs = Vacancy.objects.filter(category__name=category)
        return qs


class VacancyStateFilter(VacancyHome):
    template_name = "vacancies/state_filter.html"

    def get_queryset(self):
        state = self.kwargs.get("state", None)

        qs = Vacancy.objects.filter(state__name=state)
        return qs


def send_vacancy(request):
    if request.method == "POST":
        form = VacancyForm(request.POST)
        if form.is_valid():
            vacancy = form.save(commit=False)
            vacancy.owner = request.user
            vacancy.save()
            messages.success(request, "Vacancy sent")
            return redirect("vacancies:home")
    else:
        form = VacancyForm(user=request.user)
        return render(request, "vacancies/send_vacancy.html", {"form": form})


def delete_vacancy(request, pk):
    obj = Vacancy.objects.get(id=pk)
    obj.delete()
    messages.warning(request, "Vacancy deleted")
    return redirect("vacancies:my_vacancies")

vacancies/templates/vacancies/detail.html
{% extends 'base.html' %}

{% block content %}


<div class="container-fluid detail mt-3">

  <div class="container detail-path h5 pb-3">
    <span class="">
      <a class="text-success" href="{% url 'vacancies:home' %}">Home</a> /
      <a class="text-success" href="{% url 'vacancies:home' %}">Vacancies</a> /
      <a class="text-success" href="{% url 'vacancies:vacancy_detail' vacancy.id %}">{{ vacancy.name }} | {{ vacancy.city }} - {{ vacancy.state }}</a>
    </span>
  </div>

  <div class="container shadow-lg p-dcontainer mb-5 bg-white rounded">

        <h2 class="mb-dtitle text-dark pt-0 q pl-3">
            Vacancy - <strong>{{ vacancy.name|upper }}</strong> {{ vacancy.city }} - {{ vacancy.state }} | {{ vacancy.number }} Vaga(s)
        </h2>
        <div class="mb-5 pl-3">
          <span>
            <a href="" class="btn btn-success">Job | {{ vacancy.occupation_area }}</a> {{ vacancy.city }} -
            <a href="{% url 'vacancies:state_filter' vacancy.state %}" class="text-dark pl-dlocation"> {{ vacancy.state }}</a>
          </span>
        </div>
            <ul class="list-group">
                <li class="list-group-item">
                    <p class="detail-p">Location</p>
                    {{ vacancy.city }},
                    {{ vacancy.state.get_name_display }}
                </li>
                <li class="list-group-item">
                    <p class="detail-p">Vacancy</p>
                    {{ vacancy.name }} -
                    {{ vacancy.number }} Vagas(s)
                </li>
                <li class="list-group-item">
                    <p class="detail-p">Salary</p>
                    {{ vacancy.salary }}
                </li>
              </ul>
              <div class="accordion mt-3" id="accordionExample">
                <div class="card pt-2">
                  <div class="card-header" id="headingOne">
                    <h5 class="mb-0">
                      <button class="btn btn-light" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        ABOUT YHE COMPANAY
                      </button>
                    </h5>
                  </div>

                  <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
                    <div class="card-body p-dcollapse">
                    {{ vacancy.about_company }}

                    </div>
                  </div>
                </div>
                <div class="card pt-2">
                  <div class="card-header" id="headingTwo">
                    <h5 class="mb-0">
                      <button class="btn btn-light collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                        REQUERIMENTS
                      </button>
                    </h5>
                  </div>
                  <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                    <div class="card-body p-dcollapse">
                    {{ vacancy.requirements }}

                    </div>
                  </div>
                </div>
                <div class="card pt-2">
                  <div class="card-header" bg-light id="headingThree">
                    <h5 class="mb-0">
                      <button class="btn btn-light collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                        ACTIVITIES
                      </button>
                    </h5>
                  </div>
                  <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
                    <div class="card-body p-dcollapse">
                        {{ vacancy.activities }}
                    </div>
                  </div>
                  <li class="list-group-item mt-3 p-5 align-center">
                    <p class="detail-p text-center"><strong>Curriculum</strong></p>
                    Interessados(as) e que atendam o perfil solicitado acima, devem enviar seus curriculos para o e-mail
                    <strong>{{ vacancy.contact_email }}</strong> contendo no titulo/assunto <strong>{{ vacancy.name }} - {{ vacancy.state }}</strong> ou
                     atraves do telefone/WhatsApp <strong class="text-primary">{{ vacancy.contact_whatsapp }} / {{ vacancy.contact_number }} </strong>
                </li>
                </div>
              </div>
        </div>

{% endblock content %}

vacancies/templates/vacancies/form.html
{% extends 'base.html' %}

{% block content %}
<div class="container container-form border rounded shadow mb-5 mt-5">
    <h1 class="register-title p-2 pb-4 font-weight-bold">User Registration</h1>
    <form method="post" action="">
        <fieldset class="form-group border rounded">
            <legend class="text-success font-weight-bold">Personal data</legend>
            <div class="form-group row">
                <label for="" class="col-sm-2 col-form-label">First name <strong class="text-danger">*</strong></label>
                <div class="col-sm-10">
                    <input type="text" class="form-control form-input">
                </div>

            </div>

            <div class="form-group row">
                <label for="" class="col-sm-2 col-form-label">Surname</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control form-input">
                </div>
            </div>
            <div class="row">
                <legend class="col-form-label col-sm-2 pt-0">Gender</legend>
                <div class="col-sm-10">
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios1" value="option1"
                            checked>
                        <label class="form-check-label" for="gridRadios1">
                            Male
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios2" value="option2">
                        <label class="form-check-label" for="gridRadios2">
                            Female
                        </label>
                    </div>
                </div>
            </div>
        </fieldset>

        <fieldset class="form-group border rounded ">
            <legend class="text-success font-weight-bold">Contact details</legend>
            <div class="form-group row">
                <label for="" class="col-sm-2 col-form-label">E-mail <strong class="text-danger">*</strong></label>
                <div class="col-sm-10">
                    <input type="email" class="form-control form-input" id="" placeholder="Email">
                </div>
            </div>

            <div class="form-group row">
                <label for="" class="col-sm-2 col-form-label">WhatsApp <strong class="text-danger">*</strong></label>
                <div class="col-sm-10">
                    <input type="number" class="form-control form-input" id="" placeholder="Only numbers">
                </div>
            </div>
            <div class="form-group row">
                <label for="" class="col-sm-2 col-form-label">Phone number</label>
                <div class="col-sm-10">
                    <input type="number" class="form-control form-input" id="" placeholder="Only numbers">
                </div>
            </div>
        </fieldset>

        <fieldset class="form-group border rounded ">
            <legend class="text-success font-weight-bold">Profile</legend>
            <div class="form-group row">
                <label for="" class="col-sm-2 col-form-label">Occupation</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control form-input" id="" placeholder="Email">
                </div>
            </div>

            <div class="form-group row">
                <label for="" class="col-sm-2 col-form-label">Schooling <strong class="text-danger">*</strong></label>
                <div class="col-sm-10">
                    <select class="custom-select custom-select-sm mb-3">
                        <option selected>Select...</option>
                        <option value="1">Elementary school</option>
                        <option value="2">High School</option>
                        <option value="3">Graduate school</option>
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label for="" class="col-sm-2 col-form-label">User type <strong class="text-danger">*</strong></label>
                <div class="col-sm-10">
                    <select class="custom-select custom-select-sm mb-3">
                        <option selected>Select...</option>
                        <option value="1">Legal person</option>
                        <option value="2">Natural person</option>
                    </select>
                </div>
            </div>
            <div class="control">
                <div class="form-group">
                    <label for="">About you</label>
                    <textarea class="form-control" rows="3" cols="50"></textarea>
                    <small>Write a brief summary that describes you professionally.</small>
                </div>
            </div>
        </fieldset>
        <fieldset class="form-group border rounded pr-4">
            <legend class="text-success font-weight-bold">Address</legend>
            <div class="form-group row">
                <label for="" class="col-sm-2 col-form-label">Address</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control form-input" placeholder="Street, number, etc...  ">
                </div>
            </div>
            <div class="form-group row">
                <label for="" class="col-sm-2 col-form-label">Zip code</label>
                <div class="col-sm-10">
                    <input type="number" class="form-control form-input" placeholder="00000-00">
                </div>
            </div>
            <div class="form-group row">
                <label for="" class="col-sm-2 col-form-label">Neighborhood</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control form-input">
                </div>
            </div>
            <div class="form-group row">
                <label for="" class="col-sm-2 col-form-label">City</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control form-input">
                </div>
            </div>
            <div class="form-group row">
                <label for="" class="col-sm-2 col-form-label">State</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control form-input" id="" placeholder="Email">
                </div>
            </div>
        </fieldset>
        <fieldset class="form-group border rounded ">
            <legend class="text-success font-weight-bold">Access  <strong class="text-danger">*</strong></legend>
            <div class="form-group row">
                <label for="" class="col-sm-2 col-form-label">Password</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control form-input">
                </div>
            </div>
            <div class="form-group row">
                <label for="" class="col-sm-2 col-form-label">Repeat password</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control form-input">
                </div>
            </div>
        </fieldset>
        <input type="submit" class="btn btn-success mb-4" value="Register">
    </form>
</div>

{% endblock content %}

vacancies/templates/vacancies/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
        <h5{% if message.tags %} class=" li-message {{ message.tags }}"{% endif %}>{{ message }}
            <button onclick="closeMessage()" class="close">&times;</button>
        </h5>
    {% endfor %}
</ul>
{% endif %}
<div class="container-fluid mb-1 p-0">
    <div class="container-fluid bg-banner flex">
        <img src="{% static 'img/ba.png' %}" class="img-fluid" alt="">
        <div class="banner-title">
            <h1 class="banner-title main-text text-center">
                {% if request.user.is_authenticated %}
                    <a href="{% url 'user:user_profile' %}" class="title-link border rounded
                    text-white p-1 shadow rounded">Connect</a>
                    with Opportunities
                {% else %}
                    <a href="{% url 'user:user_register' %}" class="title-link border rounded
                    text-white p-1 shadow rounded">Connect</a>
                    with Opportunities
                {% endif %}
            </h1>
            <h2 class="banner-title text-center">Search for vacancies here</h2>
        </div>
    </div>
    <div class="container">
        <div class="input-group input-group-mobile">
            <form class="form-filter" action="{% url 'vacancies:vacancy_search' %}" method="get">
                <div class="input-group-prepend">
                    <button type="button" class="btn btn-category-filter btn-outline-dark dropdown-toggle dropdown-toggle-split category_display"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Categories
                    </button>

                    <div class="dropdown-menu">
                        {% for category in categories %}
                            <a href="{% url 'vacancies:vacancy_category' category.name %}" class="dropdown-item btn">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-caret-right-fill mr-2" viewBox="0 0 16 16">
                                    <path d="m12.14 8.753-5.482 4.796c-.646.566-1.658.106-1.658-.753V3.204a1 1 0 0 1 1.659-.753l5.48 4.796a1 1 0 0 1 0 1.506z"/>
                                </svg>
                            {{ category.name }}</a>
                        {% endfor %}
                    </div>
                </div>
                    <select name="occupation" class="custom-select" id="inputGroupSelect01" >
                        <option selected disabled>Occupation</option>
                        {% for occupation in all_occupations %}
                            <option>{{ occupation }}</option>
                        {% endfor %}
                    </select>

                    <select class="custom-select" id="inputGroupSelect02" name="state">
                        <option selected disabled>State</option>
                        {% for state in all_states %}
                            <option>{{ state }}</option>
                        {% endfor %}
                    </select>

                <input type="search" name="search" class="form-control input-form" value="{{ request.GET.search }}" placeholder="Profession, Job Role, etc...">

                <button type="submit" value="{{ request.GET.search }}" class="btn btn-dark">
                    <span class="mr-1 submit-filter">Filter</span>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search"
                    viewBox="0 0 16 16">
                    <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0
                    1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                    </svg>
                </button>

            </form>
        </div>
        <br>
        <div class="row">
            {% for vacancy in vacancies %}
            <div class="col-sm">
                <div class="vacancy-card shadow-card p-3 mb-5 rounded border-bottom-0">
                    <p class="p-2 vacancy-descri">
                        <small>
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                class="bi bi-calendar3" viewBox="0 0 16 16">
                                <path
                                    d="M14 0H2a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zM1 3.857C1 3.384 1.448 3 2 3h12c.552 0 1 .384 1 .857v10.286c0 .473-.448.857-1 .857H2c-.552 0-1-.384-1-.857V3.857z" />
                                <path
                                    d="M6.5 7a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm-9 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm-9 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2z" />
                            </svg>
                        </small>
                        <small id="date-sm">
                            {{vacancy.date_posted|date:"M d, Y"}}
                        </small><br>
                        <h4 class="h4">
                            <a href="{% url 'vacancies:vacancy_detail' vacancy.id %}" class="font-weight-bold link-descri">
                                {{ vacancy.name }} | {{ vacancy.city }} - {{ vacancy.state }} | {{ vacancy.number }} vaga(s)
                            </a>
                        </h4>
                    <p class="pt-3">
                        <a href="#" class=" link-descri p-1 border rounded text-white pl-2 pr-2 pt-1" id="occopation">
                            {{ vacancy.occupation_area }}
                        </a>
                    </p>
                    <p class="vacancy-locate mb-0">
                        <small id="job-sm">Emprego em
                            <a href="">{{ vacancy.city }}</a> /
                            <a href="{% url 'vacancies:state_filter' vacancy.state %}">{{ vacancy.state }}
                        </small></a>
                    </p>
                    </p>
                    {% if vacancy.img %}
                    <p><img src="{{ vacancy.img.url }}" alt=""></p>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}

vacancies/templates/vacancies/my_vacancies.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
        <h5{% if message.tags %} class=" li-message {{ message.tags }}"{% endif %}>{{ message }}
            <button onclick="closeMessage()" class="close">&times;</button>
        </h5>
    {% endfor %}
</ul>
{% endif %}

<div class="container-fluid detail mt-3">
  <div class="container my-vacancies-path h5 pb-3">
    <span class="">
      <a class="text-success" href="{% url 'vacancies:home' %}">Home</a> /
      <a class="text-success" href="{% url 'vacancies:home' %}">Vacancies</a> /
      <a class="text-success" href="{% url 'vacancies:my_vacancies' %}">My Vacancies</a>
    </span>
  </div>
</div>

<div class="container-fluid mb-1 p-0 my-vacancies-b">
  <div class="container mb-5">
      {% if not  vacancies%}
        <h1 class="text-center none-vacancies pt-3">VOCÊ NÃO POSSUI VAGAS PUBLICADAS (<a href="{% url 'vacancies:send_vacancy'%}">publicar</a>) <h1>

      {% endif %}
      <div class="row">
      {% for vacancy in vacancies %}
      <div class="col-sm">
          <div class="vacancy-card shadow-card p-3 mb-5 rounded border-bottom-0">
              <p class="p-2 vacancy-descri">
                <small>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                        class="bi bi-calendar3" viewBox="0 0 16 16">
                        <path
                            d="M14 0H2a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zM1 3.857C1 3.384 1.448 3 2 3h12c.552 0 1 .384 1 .857v10.286c0 .473-.448.857-1 .857H2c-.552 0-1-.384-1-.857V3.857z" />
                        <path
                            d="M6.5 7a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm-9 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm-9 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2z" />
                    </svg>
                </small>
                <small id="date-sm">
                    {{vacancy.date_posted|date:"M d, Y"}}
                </small><br>
                <h4 class="h4">
                    <a href="{% url 'vacancies:vacancy_detail' vacancy.id %}" class="font-weight-bold link-descri">
                        {{ vacancy.name }} | {{ vacancy.city }} - {{ vacancy.state }} | {{ vacancy.number }} vaga(s)
                    </a>
                </h4>
              <p class="pt-3">
                <a href="#" class=" link-descri p-1 border rounded text-white pl-2 pr-2 pt-1" id="occopation">
                  {{ vacancy.occupation_area }}
                </a>
                <a href="{% url 'vacancies:delete_vacancy' vacancy.id %}" class="btn btn-danger ml-2">
                  <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                  <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"></path>
                  <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"></path>
                  </svg>
                </a>
              </p>
              <p class="vacancy-locate mb-0 mt-0">
                <small id="job-sm">Emprego em
                    <a href="">{{ vacancy.city }}</a> /
                    <a href="{% url 'vacancies:state_filter' vacancy.state %}">{{ vacancy.state }}
                </small></a>
              </p>
              {% if vacancy.img %}
                <p><img src="{{ vacancy.img.url }}" alt=""></p>
              {% endif %}
          </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>



{% endblock content %}

vacancies/templates/vacancies/occupation_filter.html
{% block content %}
{% include "vacancies/index.html" %}
{% endblock content %}    

vacancies/templates/vacancies/search.html
{% extends 'vacancies/index.html' %}

vacancies/templates/vacancies/state_filter.html
{% block content %}
{% include "vacancies/index.html" %}
{% endblock content %}

vacancies/templates/vacancies/vacancy_category.html
{% block content %}
{% include "vacancies/index.html" %}
{% endblock content %}