publijob/urls.py
from django.conf import settings
from django.contrib import admin

from django.urls import include, path
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("vacancies.urls")),
    path("", include("user.urls")),
    path("summernote/", include("django_summernote.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views


app_name = "user"

urlpatterns = [
    path("user/register/", views.UserRegister.as_view(), name="user_register"),
    path("user/login/", views.UserLogin.as_view(), name="user_login"),
    path("user/logout/", views.UserLogout.as_view(), name="user_logout"),
    path("user/view_profile/", views.UserProfile.as_view(), name="user_profile"),
    path("user/edit_user/", views.EditUserInformation.as_view(), name="edit_user"),
    path(
        "profile/<int:id>/update/",
        views.edit_profile_information,
        name="update_profile",
    ),
    path(
        "user/change_password/", views.ChangePassword.as_view(), name="change_password"
    ),
]

vacancies/urls.py
from django.urls import path
from . import views


app_name = "vacancies"

urlpatterns = [
    path("", views.VacancyHome.as_view(), name="home"),
    path("vacancy/<int:pk>", views.vacancy_detail_view, name="vacancy_detail"),
    path("search/", views.VacancySearch.as_view(), name="vacancy_search"),
    path("my_vacancies/", views.MyVacancies.as_view(), name="my_vacancies"),
    path("my_vacancies/delete/<int:pk>", views.delete_vacancy, name="delete_vacancy"),
    path(
        "vacancy_category/<str:category>",
        views.VacancyCategory.as_view(),
        name="vacancy_category",
    ),
    path(
        "filter/by-state/<str:state>",
        views.VacancyStateFilter.as_view(),
        name="state_filter",
    ),
    path("send_vacancy/", views.send_vacancy, name="send_vacancy"),
]

user/models.py
from django.db import models
from choices.schooling_choices import SCHOOLING_CHOICES
from choices.stt_choices import STATE_CHOICES
from choices.user_type import USER_TYPE_CHOICES
from django.contrib.auth.models import User


class Profile(models.Model):
    username_profile = models.OneToOneField(
        User, on_delete=models.CASCADE, verbose_name="Username", null=True, blank=True
    )
    whatsapp = models.PositiveBigIntegerField("WhatsApp")
    phone_number = models.PositiveBigIntegerField("Phone number")
    occupation = models.CharField("Occupation", max_length=255)
    schooling = models.CharField(
        "Schooling",
        max_length=3,
        choices=SCHOOLING_CHOICES,
    )
    user_type = models.CharField(
        "User type",
        max_length=3,
        choices=USER_TYPE_CHOICES,
    )
    about_you = models.TextField("About you")
    address = models.CharField("Address", max_length=255)
    zip_code = models.IntegerField("Zip code")
    neighborhood = models.CharField("Neighborhood", max_length=255)
    city = models.CharField("City", max_length=255)
    state = models.CharField("State", max_length=2, choices=STATE_CHOICES)

    def __str__(self) -> str:
        return f"{self.username_profile}"

user/forms.py
from __future__ import annotations
from django import forms
from django.contrib.auth.models import User
from . import models


class ProfileForm(forms.ModelForm):
    class Meta:
        model = models.Profile
        fields = "__all__"
        exclude = ("username_profile",)


class UserForm(forms.ModelForm):
    password = forms.CharField(
        required=False,
        widget=forms.PasswordInput(),
        label="Password",
    )

    password2 = forms.CharField(
        required=False, widget=forms.PasswordInput(), label="Confirm password"
    )

    def __init__(self, user=None, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.user = user

    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "password",
            "password2",
        )

    def clean(self, *args, **kwargs):
        cleaned = self.cleaned_data
        validation_error_msgs = {}

        user_data = cleaned.get("username")
        email_data = cleaned.get("email")
        password_data = cleaned.get("password")
        password2_data = cleaned.get("password2")

        user_db = User.objects.filter(username=user_data).first()
        email_db = User.objects.filter(email=email_data).first()

        error_msg_user_exists = "Usuário já existe"
        error_msg_email_exists = "E-mail já existe"
        error_msg_password_match = "As duas senhas não conferem"
        error_msg_password_short = "Sua senha precisa de pelo menos 6 caracteres"
        error_msg_required_field = "Este campo é obrigatório."

        if not self.user:
            if user_db:
                validation_error_msgs["username"] = error_msg_user_exists

            if email_db:
                validation_error_msgs["email"] = error_msg_email_exists

            if not password_data:
                validation_error_msgs["password"] = error_msg_required_field

            if not password2_data:
                validation_error_msgs["password2"] = error_msg_required_field

            if password_data != password2_data:
                validation_error_msgs["password"] = error_msg_password_match
                validation_error_msgs["password2"] = error_msg_password_match

            if len(password_data) < 6:
                validation_error_msgs["password"] = error_msg_password_short

        if validation_error_msgs:
            raise (forms.ValidationError(validation_error_msgs))

user/views.py
from user.forms import ProfileForm
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.views import View
from django.views.generic import ListView
from . import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.views.generic.edit import UpdateView
from .models import Profile
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeView


class BaseRegister(View):
    template_name = "user/register.html"

    def setup(self, *args, **kwargs):
        super().setup(*args, **kwargs)

        self.profile = None

        if self.request.user.is_authenticated:
            self.profile = Profile.objects.filter(
                username_profile=self.request.user
            ).last()
            self.context = {
                "userform": forms.UserForm(
                    data=self.request.POST or None,
                    user=self.request.user,
                    instance=self.request.user,
                ),
                "profileform": forms.ProfileForm(
                    data=self.request.POST or None,
                    instance=self.profile,
                ),
            }

        else:
            self.context = {
                "userform": forms.UserForm(data=self.request.POST or None),
                "profileform": forms.ProfileForm(data=self.request.POST or None),
            }

        self.userform = self.context["userform"]
        self.profileform = self.context["profileform"]

        self.render = render(self.request, self.template_name, self.context)

    def get(self, *args, **kwargs):
        return self.render


class UserRegister(BaseRegister):
    def post(self, *args, **kwargs):
        if not self.userform.is_valid() or not self.profileform.is_valid():
            return self.render

        username = self.userform.cleaned_data.get("username")
        password = self.userform.cleaned_data.get("password")

        if not self.request.user.is_authenticated:
            user = self.userform.save(commit=False)
            user.set_password(password)
            user.save()

            profile = self.profileform.save(commit=False)
            profile.username_profile = user
            profile.save()

        if password:
            check = authenticate(self.request, username=username, password=password)
            if check:
                login(self.request, user=user)

        messages.success(
            self.request,
            "Successful registration.\n Fill out the form below to submit a vacancy.",
        )
        return redirect("vacancies:send_vacancy")


class UserLogin(BaseRegister):
    template_name = "user/login.html"

    def post(self, *args, **kwargs):
        username = self.request.POST.get("username")
        password = self.request.POST.get("password")

        if not username or not password:
            messages.error(self.request, "Wrong username or password")
            return redirect("user:user_login")

        user = authenticate(self.request, username=username, password=password)

        if not user:
            messages.error(self.request, "Wrong username or password")
            return redirect("user:user_login")

        login(self.request, user=user)
        messages.success(self.request, "login successful")
        return redirect("vacancies:home")


class UserLogout(BaseRegister):
    def get(self, *args, **kwargs):
        logout(self.request)
        messages.info(self.request, "You are logged out")
        return redirect("vacancies:home")


class UserProfile(ListView):
    model = Profile
    context_object_name = "profile"
    template_name = "user/profile.html"


class EditUserInformation(UpdateView):
    template_name = "user/edit.html"
    model = User
    fields = ["first_name", "last_name", "email", "username"]
    template_name_suffix = "_update_form"
    success_url = reverse_lazy("user:user_profile")

    def get_object(self):
        messages.success(self.request, "Successfully changed")
        return self.request.user


def edit_profile_information(request, id):
    profile = Profile.objects.get(id=id)
    if request.method == "POST":
        form = ProfileForm(request.POST, instance=profile)
        if form.is_valid():
            form.save()

            messages.success(request, "Successfully changed")
            return redirect("user:user_profile")
    else:
        form = ProfileForm(instance=profile)

    return render(request, "user/profile_update.html", {"form": form})


class ChangePassword(PasswordChangeView):
    template_name = "user/change_password.html"
    form_class = PasswordChangeForm
    success_url = reverse_lazy("vacancies:home")

    # def get(self):
    #     messages.success(self.request, 'Successfully changed')
    #     return

user/templates/user/change_password.html
{% extends 'base.html' %}
{% load widget_tweaks %}


{% block content %}
<div class="container-fluid mb-5 mt-3">
  <div class="container changepassword-path h5 pb-0">
    <span class="">
      <a class="text-success" href="{% url 'vacancies:home' %}">Home</a> /
      <a class="text-success" href="{% url  'user:user_profile'%}">Change password</a>
    </span>
  </div>

  <div class="container container-form border rounded shadow">
    <h1 class="p-2 pb-4 text-success font-weight-bold">Change password</h1>
    <form method="post">
      {% csrf_token %}
      {% for field in form.visible_fields %}
      <div class="form-group pl-2 pr-2">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field|add_class:'form-control' }}
        {% for error in field.errors %}
        <span class="help-block">{{ error }}</span>
        {% endfor %}
      </div>
      {% endfor %}

      <input class="btn btn-dark change-btn-mobile change-btn mt-1 ml-2" type="submit" value="Update">
    </form>

  </div>
</div>
{% endblock content %}

user/templates/user/edit.html
{% extends 'base.html' %}
{% load widget_tweaks %}


{% block content %}
<div class="container-fluid mb-5 mt-3">
  <div class="container changepassword-path h5 pb-0">
    <span class="">
      <a class="text-success" href="{% url 'vacancies:home'%}">Home</a> /
      <a class="text-success" href="{% url 'user:user_profile'%}">Profile</a> /
      <a class="text-success" href="{% url 'user:edit_user'%}">Change data</a>
    </span>
  </div>
  <div class="container container-form border rounded shadow mt-4">

    <h1 class="p-2 pb-4 text-success font-weight-bold">Change data</h1>
    <form method="post">
      {% csrf_token %}
      {% for field in form.visible_fields %}
      <div class="form-group pl-2 pr-1">
          <label for="{{ field.id_for_label }}">{{ field.label }}</label>
          {{ field|add_class:'form-control form-font' }}
          {% for error in field.errors %}
          <span class="help-block">{{ error }}</span>
          {% endfor %}
      </div>
      {% endfor %}

      <input class="btn btn-dark change-btn-mobile change-btn mt-1 ml-2" type="submit" value="Update">
    </form>

  </div>
</div>
{% endblock content %}

user/templates/user/edit_profile.html
{% extends 'base.html' %}

<form action="">
    {{ form.as_p }}
</form>

user/templates/user/login.html
{% extends 'base.html' %}


{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
        <h5{% if message.tags %} class=" li-message {{ message.tags }}"{% endif %}>{{ message }}
            <button onclick="closeMessage()" class="close">&times;</button>
        </h5>
    {% endfor %}
</ul>
{% endif %}
<div class="container container-form pt-3">
  <div class="container login-one-path h5 pb-3">
    <span class="">
      <a class="text-success" href="{% url 'vacancies:home' %}">Home</a> /
      <a class="text-success" href="{% url  'user:user_login'%}">Login</a>
    </span>
  </div>
  <form class="p-5 mt-0 shadow border rounded register-form" method="post" action="{% url 'user:user_login' %}">
    {% csrf_token %}
    <fieldset class="form-group rounded">
      <legend class="p-0 m-0 font-weight-bold text-dark register-legend">Login</legend>
      <div class="form-group">
        <label for="InputUser1">Username</label>
        <input type="text" class="form-control" id="exampleInputEmail1" name="username" aria-describedby="emailHelp">
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <input type="password" class="form-control" id="exampleInputPassword1" name="password">
      </div>
      <button type="submit" class="btn btn-success">Sing in</button>
    </form>
    <a href="{% url 'user:user_register' %}" class="float-right text-decoration-none">Or register now</a>
  </fieldset>
</div>
{% endblock content %}

user/templates/user/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
        <h5{% if message.tags %} class="li-message {{ message.tags }}"{% endif %}>{{ message }}
            <button onclick="closeMessage()" class="close">&times;</button>
        </h5>
    {% endfor %}
</ul>
{% endif %}
<section class="section-profile">
    <div class="container pt-3">
      <div class="container register-profile-path h5 pb-3">
        <span class="">
          <a class="text-success" href="{% url 'vacancies:home' %}">Home</a> /
          <a class="text-success" href="{% url  'user:user_profile'%}">Profile</a>
        </span>
      </div>
      <div class="row">
        <div class="col-lg-4">
          <div class="card mb-4 shadow-sm card-size p-3 mb-5 bg-white rounded">
            <div class="card-body text-center">
              <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava3.webp" alt="avatar"
                class="rounded-circle img-fluid" style="width: 150px;">
              <h5 class="my-3">{{ user.profile.username_profile }}</h5>
              <p class="text-muted mb-1">{{ user.profile.occupation }}</p>
              <p class="text-muted mb-4">{{ user.profile.neighborhood }}, {{ user.profile.city }}, {{ user.profile.state }}</p>
              <div class="mb-2">

              <div class="mb-2">
                {% if request.user.is_authenticated %}
                  {% for profile in all_profiles %}
                      {% if profile.username_profile == request.user.profile.username_profile %}
                          <a class="btn btn-outline-success pt-1 pb-1" href="{% url 'user:update_profile' profile.id %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil mr-1" viewBox="0 0 16 16">
                              <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                          </svg>
                          Edit profile</a>
                      {% endif %}
                  {% endfor %}
                {% endif %}
              </div>

                <div>
                  <a href="{% url 'user:edit_user' %}" class="btn btn-success pt-1 pb-1">
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil mr-1" viewBox="0 0 16 16">
                          <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                      </svg>
                  Edit user</a>
                </div>
              </div>
            </div>
          </div>

        </div>
        <div class="col-lg-8 ">
          <div class="card mb-4 card-size shadow-sm p-3 mb-5 bg-white rounded">
            <div class="card-body">
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Full Name</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted">{{ user.first_name }} {{ user.last_name }}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Email</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted">{{ user.email }}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Phone</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted">{{ user.profile.phone_number }}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Mobile</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted">{{ user.profile.whatsapp }}</p>
                </div>
              </div>
              <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Address</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted">
                  <strong>Zip code</strong>: {{ user.profile.zip_code }}
                  {{ user.profile.address }}, {{ user.profile.neighborhood }},
                  {{ user.profile.city }}, {{ user.profile.state }}</p>
              </div>
            </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

user/templates/user/profile_update.html
{% extends 'base.html' %}
{% load widget_tweaks %}


{% block content %}
<div class="container-fluid mb-5 mt-3">
  <div class="container changepassword-path h5 pb-0">
    <span class="">
      <a class="text-success" href="{% url 'vacancies:home'%}">Home</a> /
      <a class="text-success" href="{% url 'user:user_profile'%}">Profile</a> /
      <a class="text-success" href="{% url 'user:update_profile' request.user.profile.id %}">Update profile</a>
    </span>
  </div>
  <div class="container container-form border rounded shadow mt-4">

    <h1 class="p-2 pb-4 text-success font-weight-bold">Change data</h1>
    <form method="post">
      {% csrf_token %}
      {% for field in form.visible_fields %}
      <div class="form-group pl-2 pr-1">
          <label for="{{ field.id_for_label }}">{{ field.label }}</label>
          {{ field|add_class:'form-control form-font' }}
          {% for error in field.errors %}
          <span class="help-block">{{ error }}</span>
          {% endfor %}
      </div>
      {% endfor %}

      <input class="btn btn-dark change-btn-mobile change-btn mt-1 ml-2" type="submit" value="Update">
    </form>

  </div>
</div>
{% endblock content %}

user/templates/user/register.html
{% extends 'base.html' %}
{% load  crispy_forms_tags%}


{% block content %}
<div class="container container-form pt-3">
    <div class="container register-profile-path h5 pb-3">
        <span class="">
          <a class="text-success" href="{% url 'vacancies:home' %}">Home</a> /
          <a class="text-success" href="{% url  'user:user_register'%}">Register</a>
        </span>
      </div>
    <form class="p-5 mt-0 shadow border rounded register-form" action="" method="post">
        <fieldset class="form-group border rounded">
            <legend class="p-0 m-0 font-weight-bold text-success register-legend">User Registration</legend>
            {%csrf_token%}
            {{ userform|crispy }}
            {{ profileform|crispy }}
        <input class="btn btn-success" type="submit" value="Submit">
    </form>
</div>
{% endblock content %}